### ISSUE TITLE
[bug]lock feature doesn't work a21.1

### ISSUE THREAD

**Issue by Layarion** [Westwud1/QuickStack#15]
it's the only mod installed, LAlt+Click does not lock anything. LAlt+X does stack items into nearby existing stacks though.

Please get the lock working, this would make life so much easier.

**Comment by Westwud1** [comment]
Do you have other mods installed, how can I reproduce this issue?

**Comment by Layarion** [comment]
> Do you have other mods installed, how can I reproduce this issue?

I did originally, but i uninstalled all mods and tried this one solo, and still got the issue. I guess you're saying it's working when you try it?

hmmm...

i am on windows 11, though i doubt that's the problem...i can only guess that maybe i had a lingering side effect from a mod still on it, or my pc was missing something that your pc has.

i suppose i could delete my entire 7days directory, clean out the appdata, and try it again...

**Comment by Layarion** [comment]
also, is your name a RedAlert reference?

**Comment by Westwud1** [comment]
> I did originally, but i uninstalled all mods and tried this one solo, and still got the issue. I guess you're saying it's working when you try it?

Yes, it should work, just updated for A21.2 and tested it again and it works.

> i am on windows 11, though i doubt that's the problem...i can only guess that maybe i had a lingering side effect from a mod still on it, or my pc was missing something that your pc has.

I don't think it's a Win11 issue, you could try verifying integrity of game files via steam, that should reset your install to default besides the Mods folder. Another thing may be if the game is installed from Steam or Microsoft store. I'd try on a new game as well.

> also, is your name a RedAlert reference?

Yes, one of the first games I played. When choosing a name for some game or login (don't remember), "Westwood" was used hence the "Westwud" adaptation :).

**Comment by Layarion** [comment]
> Yes, one of the first games I played. When choosing a name for some game or login (don't remember), "Westwood" was used hence the "Westwud" adaptation :)

ya same here, one of the first PC games i played. those cheesy cut scenes and killer music had me hooked. it was good times when games won you on atmosphere alone.

**Comment by Layarion** [comment]
-update: i was able to get this to work with my personal inventory (it's the only mod installed). it's a red border that shows up around the locked slot correct?

well i can't get it to work inside chest. also, it doesn't seem to do anything. i for example, lock wood into the third slot at the top left of my inventory, and take the wood out. when i put another item into my inventory, it allows that slot to be filled. so i'm not sure it's working correctly.

-could you update the 7days homepage to describe what the lock slot actually does, it just says that it locks it, not what a lock does. also it doesn't describe what it looks like either.

**Comment by Westwud1** [comment]
Again, sorry for the late update.

Slot locking works only on the player inventory, so no chests, drones or vehicles. The lock only prevents you from moving locked items from your inventory to the chests, but you are able to take items from chests to your inventory and fill up locked slots.

For example you have ammo, food, water which are locked and it would make sense if you want to refill (restock) them. But you don't want to put all of them in the chests by clicking on quickstack to deposit other items. I think it is intuitive to use and the idea for the mod is from terraria if you've ever played it.
