### ISSUE TITLE
District Zero v1.2.4 sort inventory button overlaps with quick stack buttons 

### ISSUE THREAD

**Issue by youngchan01** [Westwud1/QuickStack#16]
In Alpha 21.1.16, District Zero v1.2.4 installed and quickstack installed, the quickstack buttons overlaps with the sort inventory button in the inventory UI.

I see that in nexus mods you've provided fixes for Darkness Falls and War3zuk, I have tried the solution for Darkness Falls, but that didn't work. 

Would you be able to look into a fix for this?

**Comment by Westwud1** [comment]
Those were provided by other people, I've just added them in the description. Unfortunately I do not have the time to do compatibiltiy patches with other mods.
