### ISSUE TITLE
QuickStack for b317+

### ISSUE THREAD

**Issue by DanzoGit** [Westwud1/QuickStack#18]
This is a recompiled version for b317 (and possibly higher). You can use this until Westwud updates the mod. Put the contents in a folder with file replacement.
[QuickStack.zip](https://github.com/user-attachments/files/16250257/QuickStack.zip)

**Comment by CmdShft4** [comment]
Very nice! Thanks so much. I tried to figure out if I could fix the problem, but it was over my head immediately. I can mess with XML, but compiling and dlls make me nervous.

Again, thanks. I already had my 1.0 family server set up and it broke going from 313 to 316. It literally made my dedicated server (SteamCMD) stop loading. I had to remove all the mods and restore one at a time until I found that QuickStack was the issue.

Keep up the great work. I really appreciate the QoL improvement.

**Comment by Westwud1** [comment]
Thanks. Mod is recompiled again for b317 + some other bug fixes and features.
